"""factures et fiches de paie

Revision ID: 01f01431386b
Revises: 94da9071c120
Create Date: 2026-09-28 12:10:49.596907

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '01f01431386b'
down_revision: Union[str, Sequence[str], None] = '94da9071c120'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('period', sa.String(length=7), nullable=True))
    op.add_column('documents', sa.Column('direction', sa.String(), nullable=True))
    op.drop_constraint(op.f('uq_company_doc_kind'), 'documents', type_='unique')
    op.create_index('ix_documents_company_period', 'documents', ['company_id', 'period'], unique=False)
    op.create_index('uq_company_onboarding_kind', 'documents', ['company_id', 'kind'], unique=True, postgresql_where=sa.text("kind IN ('PATENTE', 'RNE')"))
    op.create_index('uq_company_sha256_pieces', 'documents', ['company_id', 'sha256'], unique=True, postgresql_where=sa.text("kind IN ('FACTURE', 'FICHE_PAIE')"))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_company_sha256_pieces', table_name='documents', postgresql_where=sa.text("kind IN ('FACTURE', 'FICHE_PAIE')"))
    op.drop_index('uq_company_onboarding_kind', table_name='documents', postgresql_where=sa.text("kind IN ('PATENTE', 'RNE')"))
    op.drop_index('ix_documents_company_period', table_name='documents')
    op.create_unique_constraint(op.f('uq_company_doc_kind'), 'documents', ['company_id', 'kind'], postgresql_nulls_not_distinct=False)
    op.drop_column('documents', 'direction')
    op.drop_column('documents', 'period')
    # ### end Alembic commands ###
